# -*- coding: utf-8 -*-
"""map.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x3Hes15tpBKKpBoZmhv4nShi8jVXwyRT
"""

#map
mylist=[10,20,30]
def square(num):
  return num**2
list(map(square,mylist))

#exceptional handling
#try==>code to run
#except==>error occurs
#finally==>
try:
  print(10)
  print(num123)
except (NameError,TypeError) as e:
  print("error occured",e)
except Exception as e:
  print("all error occured",e)
finally:
  print("hey")

